=== rcp0015/1DAM_LMSG_Rodrigo/Tema10/Ejemplo_dtd.dtd
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (nombre+,autor+, editorial?,paginas,(precio|precio_con_iva))>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT paginas (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT precio_con_iva (#PCDATA)>

=== rcp0015/1DAM_LMSG_Rodrigo/Tema10/EjemploDTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca  SYSTEM "Ejemplo_dtd.dtd">
<biblioteca>
    <libro>
        <nombre>Introduccion a xml</nombre>
        <autor>Pedro Martinez</autor>
        <autor>Alberto Ruiz</autor>
        <editorial>Parainfo</editorial>
        <paginas>345</paginas>
        <precio>45</precio>
    </libro>

        <libro>     
        <nombre>CSS3</nombre>
        <nombre>CSS3</nombre>
        <autor>Luis Ruiz</autor>
        <editorial>Sintesis</editorial>
        <paginas>234</paginas>
        <precio_con_iva>45</precio_con_iva>
    </libro>

    <libro>
        <nombre>El se√±or de los anillos</nombre>
        <autor> Tolkien</autor>
        <paginas>234</paginas>
        <precio>34</precio>
    </libro>
</biblioteca>
