=== rcp0015/1DAM_LMSG_Rodrigo/Validacion XML Schema/componentes.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="listacomponentes">
<xs:complexType>
    <xs:sequence>
        <xs:element name="componente"> 
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="marca" type="xs:string"></xs:element>
                    <xs:element name= "modelo" type="xs:string"></xs:element>
                    <xs:element name="categoria" type="xs:string"></xs:element>
                   
                    <xs:element name="precio" type="xs:float"></xs:element>
                     <!-- ELEGIR -->
                    <xs:choice> 

                    <xs:element name="stock" type="xs:unsignedShort"></xs:element> 
                     <xs:element name="cantidad" type="xs:unsignedShort" ></xs:element> 
                     </xs:choice>
                    <xs:element name="fecha_alta" type="xs:date"></xs:element> 
                    <xs:element name="garantia" type="xs:integer" ></xs:element> 
                    <xs:element name="color" type="xs:string"></xs:element>
                    <xs:element name="cliente_reserva" type="xs:string" maxOccurs="2"></xs:element> 
                    <xs:element name="extras" minOccurs="0" maxOccurs="2" type="xs:string"></xs:element>
                </xs:sequence>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
    <xs:attribute name="stock" type="xs:unsignedShort" use="optional"></xs:attribute>
    <xs:attribute name="fecha_alta" type="xs:date" use="required"></xs:attribute>
    <xs:attribute name="garantia" type="xs:integer" use="optional"></xs:attribute>
    <xs:attribute name="color" type="xs:string" use="optional"></xs:attribute>
    <xs:attribute name="cantidad" type="xs:unsignedShort" use="optional"></xs:attribute>
</xs:complexType>
</xs:element>

<!-- CATEGORIA -->
<xs:simpleType name="categoria" >
    <xs:restriction base="xs:string">
        <xs:enumeration value="CPU"></xs:enumeration>
         <xs:enumeration value="GPU"></xs:enumeration>
        <xs:enumeration value="RAM"></xs:enumeration>
    </xs:restriction>
</xs:simpleType>

<!-- DE 1 A 300 -->
  <xs:simpleType name="precio">
        <xs:restriction base="xs:float">
            <xs:minInclusive value="1"></xs:minInclusive>
            <xs:maxInclusive value="300"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <!-- 6 A 60 MESES  -->
      <xs:simpleType name="garantia">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="6"></xs:minInclusive>
            <xs:maxInclusive value="60"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <!-- DNI -->
    <xs:simpleType name="cliente_reserva" >
        <xs:restriction base="xs:string" >
            <xs:pattern value="\d{8}[A-Z]" ></xs:pattern>
        </xs:restriction>
     </xs:simpleType>
</xs:schema>

=== rcp0015/1DAM_LMSG_Rodrigo/Validacion XML Schema/componentes.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<listacomponentes
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="componentes.xsd">

  <componente tipo="CPU">
    <marca>Intel</marca>
    <modelo>i5-12400F</modelo>
    <categoria>CPU</categoria>
    <precio>180</precio>
    <stock>12</stock>
    <fecha_alta>2025-10-05</fecha_alta>
    <garantia>24</garantia>
    <color>Negro</color>
    <cliente_reserva>12345678Z</cliente_reserva>
    <cliente_reserva>87654321H</cliente_reserva>
    <extras>Disipador PastaTermica</extras>
  </componente>

  <componente tipo="GPU">
    <marca>NVIDIA</marca>
    <modelo>RTX4060</modelo>
    <categoria>GPU</categoria>
    <precio>299.99</precio>
    <cantidad>3</cantidad>
    <fecha_alta>2025-11-20</fecha_alta>
    <garantia>36</garantia>
    <extras>Backplate Manual</extras>
  </componente>

  <componente tipo="RAM">
    <marca>Corsair</marca>
    <modelo>Vengeance16GB</modelo>
    <categoria>RAM</categoria>
    <precio>75</precio>
    <fecha_alta>2025-09-12</fecha_alta>
    <color>Blanco</color>
  </componente>
</listacomponentes>
