=== rcp0015/1DAM_LMSG_Rodrigo/Tema11/Ejemplo2/Clientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ListaClientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente" type="xs:string" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="apellido" type="xs:string"></xs:element>
                            <xs:choice>
                                <xs:element name="dni" type="xs:string"></xs:element>
                                <xs:element name="nie" type="xs:string"></xs:element>
                            </xs:choice>
                            <xs:element name="compras" type="xs:integer"></xs:element>
                            <xs:element name="regalo" type="xs:string" minOccurs="0"
                                maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="matricula" type="xs:string" use="required"></xs:attribute>
                        <xs:attribute name="espaÃ±ol" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rcp0015/1DAM_LMSG_Rodrigo/Tema11/Ejemplo2/Clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<ListaClientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Clientes.xsd">

<cliente español ="si">
    <nombre>Juan</nombre>
    <apellido>Marmol</apellido>
    <dni>12345678A</dni>
    <compras>4500</compras>
    <regalo>bolsa de deporte</regalo>
</cliente>

<cliente español ="no">
    <nombre>Ana </nombre>
    <apellido>Gonzalez</apellido>
    <nie>87654321B</nie>
    <compras>1600</compras>
</cliente>
</ListaClientes>
