=== rcp0015/1DAM_LMSG_Rodrigo/Tema11/Ejermplo5/Ejemplo3/Concesionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Concesionario">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="coche" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="matricula" type="xs:string"></xs:element>
                            <xs:element name="marca" type="xs:string"></xs:element>
                            <xs:element name="modelos" type="xs:string"></xs:element>
                            <xs:choice>
                                <xs:element name="cilindrada" type="xs:decimal"></xs:element>
                                <xs:element name="caballos" type="xs:string"></xs:element>
                            </xs:choice>
                            <xs:element name="combustible" type="xs:string"></xs:element>
                            <xs:element name="precio" type="xs:string"></xs:element>
                            <xs:element name="año" type="xs:unsignedShort" minOccurs="0"></xs:element>
                            <xs:element name="color" type="xs:string"></xs:element>
                            <xs:element name="interesado" type="xs:string" minOccurs="0"
                                maxOccurs="unbounded"></xs:element>
                            <xs:element name="accesorios" minOccurs="0" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="año" type="xs:unsignedShort" use="optional"></xs:attribute>
                        <xs:attribute name="interesado" type="xs:string" use="optional"></xs:attribute>
                    
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
            <xs:attribute name="provincia" type="xs:string" use="required"></xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- TIPO DE COMBUSTIBLE-->

    <xs:simpleType name="combustible">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Diesel"></xs:enumeration>
            <xs:enumeration value="Gasolina"></xs:enumeration>
            <xs:enumeration value="diesel"></xs:enumeration>
            <xs:enumeration value="gasolina"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <!-- MAXIMO Y MINIMO DE CABALLOS-->

    <xs:simpleType name="caballos">
        <xs:restriction base="xs:unsignedShort">
            <xs:minInclusive value="60"></xs:minInclusive>
            <xs:maxInclusive value="180"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <!-- AÑOS DE 4 CIFRAS-->

     <xs:simpleType name="año">
        <xs:restriction base="xs:unsignedShort">
            <xs:totalDigits value="4"></xs:totalDigits>
        </xs:restriction>
     </xs:simpleType>

<!--DNI -->
     <xs:simpleType name="interesado">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{8}[A-Z]"></xs:pattern>
        </xs:restriction>
     </xs:simpleType>

     <!-- NUMERO DE ACCESORIOS-->
<xs:simpleType name="accesorios">
    <xs:list itemType="xs:string"></xs:list>
</xs:simpleType>

<xs:simpleType name="tresaccesosios">
    <xs:restriction base="accesorios">
        <xs:maxLength value="3"></xs:maxLength>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== rcp0015/1DAM_LMSG_Rodrigo/Tema11/Ejermplo5/Ejemplo3/Concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<Concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Concesionario.xsd" provincia="Malaga">

    <coche>
        <matricula>6732KPC</matricula>
        <marca>Seat</marca>
        <modelos>Ateca</modelos>
        <cilindrada>1.7</cilindrada>
        <combustible>Diesel</combustible>
        <precio>23.000€</precio>
        <año>2018</año>
        <color>Negro</color>
        <interesado>33358697A</interesado>
        <interesado>30515455T</interesado>
        <accesorios>navegador aleron faldones</accesorios>
    </coche>

      <coche>
        <matricula>8280DGH</matricula>
        <marca>Volkswagen</marca>
        <modelos>Polo</modelos>
        <cilindrada>1.2</cilindrada>
        <combustible>Gasolina</combustible>
        <precio>5.000€</precio>
        <color>Negro</color>
        <interesado>60514553T</interesado>
    </coche>

      <coche>
        <matricula>9765DGH</matricula>
        <marca>Renault</marca>
        <modelos>Megane</modelos>
        <caballos>1,7</caballos>
        <combustible>Diesel</combustible>
        <precio>7.500€</precio>
        <año>2018</año>
        <color>Verde</color>
    </coche>
</Concesionario>
